# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "Documentation for CobaltCore"
SPDX-PackageDownloadLocation = "https://github.com/cobaltcore-dev/docs"

[[annotations]]
path = [
  "package*.json",
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".dockerignore",
  ".editorconfig",
  "docs/.vitepress/**",
  "docs/**.md",
  "hack/**"
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"
